// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package storagedb

import (
	"database/sql"
)

type Book struct {
	BookID      int32
	Title       string
	Author      string
	Price       sql.NullFloat64
	Description sql.NullString
	AuthorBio   sql.NullString
}
